BATTLE_STATUS_ROUND = 0
BATTLE_STATUS_INFINITE = 1

BATTLE_STATUS_EFFECT_SOAKED = 'soaked'

STATUS_FOLDER = 'toontown.battle.statusEffect'
STATUS_NAME_2_FILE = {BATTLE_STATUS_EFFECT_SOAKED: 'BattleStatusSoakedAI'}

STATUS_EFFECT2VISUAL_COLOR = {BATTLE_STATUS_EFFECT_SOAKED: (0.0, 0.0, 1.0, 1.0)}

STATUS_VISUAL_PIXIE_WALL = 0