BATTLE_STATUS_ROUND = 0
BATTLE_STATUS_INFINITE = 1

BATTLE_STATUS_EFFECT_SOAKED = 'soaked'

STATUS_FOLDER = 'toontown.battle.statusEffect'
STATUS_NAME_2_FILE = {BATTLE_STATUS_EFFECT_SOAKED: 'BattleStatusSoakedAI'}